#!/usr/bin/env python
"""Convert runtime/baselines/golden_seed42.json (Python torch reference)
into tools/cpp_port/tests/golden_seed42.hpp, as exact float bit patterns so
the C++ golden test can compare bit-for-bit without a JSON parser.

Regenerate with:  .venv/bin/python tools/cpp_port/tests/gen_golden.py
"""

import json
import struct
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
SRC = REPO / "runtime" / "baselines" / "golden_seed42.json"
DST = REPO / "tools" / "cpp_port" / "tests" / "golden_seed42.hpp"


def f2bits(v: float) -> int:
    return int.from_bytes(struct.pack("<f", v), "little")


def hex_to_float(h: str) -> float:
    """Capture format is struct.pack('>f'), decoded big-endian."""
    v: float = struct.unpack(">f", bytes.fromhex(h))[0]
    return v


def arr(name: str, values, cols: int = 4) -> str:
    bits = [f2bits(v) for v in values]
    lines = [f"static const uint32_t {name}[{len(bits)}] = {{"]
    for i in range(0, len(bits), cols):
        chunk = ", ".join(f"0x{b:08x}u" for b in bits[i : i + cols])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    g = json.loads(SRC.read_text())
    parts = [
        "// GENERATED by tools/cpp_port/tests/gen_golden.py. Do not edit.",
        "// Reference: Python torch, seed 42, baseline sandbox child semantics.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace distribai {",
        "namespace golden {",
        "",
        f"static const int SEED = {g['seed']};",
        f"static const int STEPS = {g['steps']};",
        f"static const int N_PARAMS = {g['n_params']};",
        f"static const int GRAD_LEN = {g['grad_len']};",
        "",
        arr(
            "RNG_FIRST8",
            [
                0.8822692513,
                0.9150039554,
                0.3828637600,
                0.9593056440,
                0.3904482126,
                0.6008953452,
                0.2565724850,
                0.7936413288,
            ],
        ),
        "",
        arr("INIT_W1_8", [hex_to_float(h) for h in g["init_hex"]["W1_row0_8"]]),
        arr("INIT_B1_8", [hex_to_float(h) for h in g["init_hex"]["b1_8"]]),
        arr("INIT_W2_8", [hex_to_float(h) for h in g["init_hex"]["W2_row0_8"]]),
        arr("INIT_W3_30", [hex_to_float(h) for h in g["init_hex"]["W3_all"]]),
        arr("INIT_B3_1", [hex_to_float(h) for h in [g["init_hex"]["b3"]]]),
        "",
        arr("LOSS_FIRST5", [hex_to_float(h) for h in g["loss_all200_hex"][:5]]),
        arr("LOSS_FINAL_1", [hex_to_float(h) for h in [g["loss_all200_hex"][-1]]]),
        arr("LOSS_ALL200", [hex_to_float(h) for h in g["loss_all200_hex"]], cols=5),
        "",
        arr("GRAD_FIRST16", [hex_to_float(h) for h in g["grad_first16_hex"]]),
        "",
        f"static const double GRAD_SUM = {g['grad_sum']!r};",
        f"static const int GRAD_FIRST3_ZERO = {int(all(v == 0.0 for v in g['grad_first3']))};",
        "",
        "}  // namespace golden",
        "}  // namespace distribai",
        "",
    ]
    DST.write_text("\n".join(parts))
    print(f"wrote {DST}")


if __name__ == "__main__":
    main()
