"""Convert Jupyter notebooks into a runnable ``run.py`` for script jobs.

Bundles may ship ``run.ipynb`` (with or without ``run.py``). The worker
writes code cells into ``run.py`` before the sandbox starts so existing
backends keep executing ``python run.py``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


class NotebookMountError(ValueError):
    """Raised when a notebook cannot be converted into executable Python."""


def _cell_source(cell: dict[str, Any]) -> str:
    source = cell.get("source", "")
    if isinstance(source, list):
        return "".join(str(part) for part in source)
    return str(source)


def ipynb_to_python(notebook: str | bytes | dict[str, Any]) -> str:
    """Extract code cells from an ``.ipynb`` document into a Python script.

    Markdown and raw cells are skipped. Magics and shell bangs that Jupyter
    would intercept are left as-is so operators see failures locally rather
    than silently rewritten semantics.
    """
    if isinstance(notebook, bytes):
        notebook = notebook.decode("utf-8")
    if isinstance(notebook, str):
        try:
            payload = json.loads(notebook)
        except json.JSONDecodeError as exc:
            raise NotebookMountError(f"invalid notebook JSON: {exc}") from exc
    else:
        payload = notebook

    if not isinstance(payload, dict):
        raise NotebookMountError("notebook root must be a JSON object")

    cells = payload.get("cells")
    if not isinstance(cells, list):
        raise NotebookMountError("notebook missing cells list")

    chunks: list[str] = [
        "# Generated by DistribAI notebook mount from run.ipynb\n",
        "# Only code cells are included; re-export if you edit the notebook.\n\n",
    ]
    code_count = 0
    for cell in cells:
        if not isinstance(cell, dict):
            continue
        if cell.get("cell_type") != "code":
            continue
        text = _cell_source(cell).rstrip()
        if not text:
            continue
        code_count += 1
        chunks.append(text)
        chunks.append("\n\n")

    if code_count == 0:
        raise NotebookMountError("notebook contains no code cells")

    return "".join(chunks).rstrip() + "\n"


def convert_ipynb_file(path: Path, *, destination: Path | None = None) -> Path:
    """Read ``path`` (``.ipynb``) and write Python to ``destination`` (default sibling ``run.py``)."""
    notebook_path = Path(path)
    if not notebook_path.is_file():
        raise NotebookMountError(f"notebook not found: {notebook_path}")
    text = ipynb_to_python(notebook_path.read_text(encoding="utf-8"))
    out = Path(destination) if destination is not None else notebook_path.with_name("run.py")
    out.write_text(text, encoding="utf-8")
    return out


def ensure_run_py(task_dir: Path) -> Path:
    """Ensure ``task_dir/run.py`` exists, converting ``run.ipynb`` when needed.

    Returns the path to ``run.py``. Raises ``NotebookMountError`` when neither
    entrypoint is usable.
    """
    root = Path(task_dir)
    run_py = root / "run.py"
    if run_py.is_file():
        return run_py

    candidates = [root / "run.ipynb"]
    candidates.extend(sorted(root.glob("*.ipynb")))
    seen: set[Path] = set()
    for candidate in candidates:
        resolved = candidate.resolve()
        if resolved in seen or not candidate.is_file():
            continue
        seen.add(resolved)
        convert_ipynb_file(candidate, destination=run_py)
        return run_py

    raise NotebookMountError("No run.py or convertible .ipynb found in package")
