# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import distribai_pb2 as distribai__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in distribai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """The central orchestrator service for handling node workflows.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSession = channel.stream_stream(
                '/distribai.NodeService/StreamSession',
                request_serializer=distribai__pb2.ClientMessage.SerializeToString,
                response_deserializer=distribai__pb2.ServerMessage.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """The central orchestrator service for handling node workflows.
    """

    def StreamSession(self, request_iterator, context):
        """A single, long-lived bidirectional stream multiplexing all control data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSession,
                    request_deserializer=distribai__pb2.ClientMessage.FromString,
                    response_serializer=distribai__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribai.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distribai.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """The central orchestrator service for handling node workflows.
    """

    @staticmethod
    def StreamSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/distribai.NodeService/StreamSession',
            distribai__pb2.ClientMessage.SerializeToString,
            distribai__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DecomposerStub(object):
    """-----------------------------------------------------------------------------
    Microservices
    -----------------------------------------------------------------------------

    Job Decomposer Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decompose = channel.unary_unary(
                '/distribai.Decomposer/Decompose',
                request_serializer=distribai__pb2.DecomposeRequest.SerializeToString,
                response_deserializer=distribai__pb2.DecomposeResponse.FromString,
                _registered_method=True)


class DecomposerServicer(object):
    """-----------------------------------------------------------------------------
    Microservices
    -----------------------------------------------------------------------------

    Job Decomposer Service
    """

    def Decompose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecomposerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decompose': grpc.unary_unary_rpc_method_handler(
                    servicer.Decompose,
                    request_deserializer=distribai__pb2.DecomposeRequest.FromString,
                    response_serializer=distribai__pb2.DecomposeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribai.Decomposer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distribai.Decomposer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Decomposer(object):
    """-----------------------------------------------------------------------------
    Microservices
    -----------------------------------------------------------------------------

    Job Decomposer Service
    """

    @staticmethod
    def Decompose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.Decomposer/Decompose',
            distribai__pb2.DecomposeRequest.SerializeToString,
            distribai__pb2.DecomposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoadBalancerStub(object):
    """Load Balancer Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Assign = channel.unary_unary(
                '/distribai.LoadBalancer/Assign',
                request_serializer=distribai__pb2.AssignRequest.SerializeToString,
                response_deserializer=distribai__pb2.AssignResponse.FromString,
                _registered_method=True)
        self.ReportCapacity = channel.unary_unary(
                '/distribai.LoadBalancer/ReportCapacity',
                request_serializer=distribai__pb2.CapacityReport.SerializeToString,
                response_deserializer=distribai__pb2.CapacityAck.FromString,
                _registered_method=True)


class LoadBalancerServicer(object):
    """Load Balancer Service
    """

    def Assign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoadBalancerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Assign': grpc.unary_unary_rpc_method_handler(
                    servicer.Assign,
                    request_deserializer=distribai__pb2.AssignRequest.FromString,
                    response_serializer=distribai__pb2.AssignResponse.SerializeToString,
            ),
            'ReportCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportCapacity,
                    request_deserializer=distribai__pb2.CapacityReport.FromString,
                    response_serializer=distribai__pb2.CapacityAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribai.LoadBalancer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distribai.LoadBalancer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoadBalancer(object):
    """Load Balancer Service
    """

    @staticmethod
    def Assign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.LoadBalancer/Assign',
            distribai__pb2.AssignRequest.SerializeToString,
            distribai__pb2.AssignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.LoadBalancer/ReportCapacity',
            distribai__pb2.CapacityReport.SerializeToString,
            distribai__pb2.CapacityAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AggregatorStub(object):
    """Aggregator Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitGradient = channel.unary_unary(
                '/distribai.Aggregator/SubmitGradient',
                request_serializer=distribai__pb2.GradientUpdate.SerializeToString,
                response_deserializer=distribai__pb2.Ack.FromString,
                _registered_method=True)
        self.Aggregate = channel.unary_unary(
                '/distribai.Aggregator/Aggregate',
                request_serializer=distribai__pb2.AggregateRequest.SerializeToString,
                response_deserializer=distribai__pb2.AggregateResponse.FromString,
                _registered_method=True)


class AggregatorServicer(object):
    """Aggregator Service
    """

    def SubmitGradient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Aggregate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGradient,
                    request_deserializer=distribai__pb2.GradientUpdate.FromString,
                    response_serializer=distribai__pb2.Ack.SerializeToString,
            ),
            'Aggregate': grpc.unary_unary_rpc_method_handler(
                    servicer.Aggregate,
                    request_deserializer=distribai__pb2.AggregateRequest.FromString,
                    response_serializer=distribai__pb2.AggregateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribai.Aggregator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distribai.Aggregator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Aggregator(object):
    """Aggregator Service
    """

    @staticmethod
    def SubmitGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.Aggregator/SubmitGradient',
            distribai__pb2.GradientUpdate.SerializeToString,
            distribai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Aggregate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.Aggregator/Aggregate',
            distribai__pb2.AggregateRequest.SerializeToString,
            distribai__pb2.AggregateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CheckpointManagerStub(object):
    """Checkpoint Manager Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreCheckpoint = channel.unary_unary(
                '/distribai.CheckpointManager/StoreCheckpoint',
                request_serializer=distribai__pb2.StoreCheckpointRequest.SerializeToString,
                response_deserializer=distribai__pb2.StoreCheckpointResponse.FromString,
                _registered_method=True)
        self.LoadCheckpoint = channel.unary_unary(
                '/distribai.CheckpointManager/LoadCheckpoint',
                request_serializer=distribai__pb2.LoadCheckpointRequest.SerializeToString,
                response_deserializer=distribai__pb2.LoadCheckpointResponse.FromString,
                _registered_method=True)
        self.ListCheckpoints = channel.unary_unary(
                '/distribai.CheckpointManager/ListCheckpoints',
                request_serializer=distribai__pb2.ListCheckpointsRequest.SerializeToString,
                response_deserializer=distribai__pb2.ListCheckpointsResponse.FromString,
                _registered_method=True)


class CheckpointManagerServicer(object):
    """Checkpoint Manager Service
    """

    def StoreCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCheckpoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckpointManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreCheckpoint,
                    request_deserializer=distribai__pb2.StoreCheckpointRequest.FromString,
                    response_serializer=distribai__pb2.StoreCheckpointResponse.SerializeToString,
            ),
            'LoadCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadCheckpoint,
                    request_deserializer=distribai__pb2.LoadCheckpointRequest.FromString,
                    response_serializer=distribai__pb2.LoadCheckpointResponse.SerializeToString,
            ),
            'ListCheckpoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckpoints,
                    request_deserializer=distribai__pb2.ListCheckpointsRequest.FromString,
                    response_serializer=distribai__pb2.ListCheckpointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribai.CheckpointManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distribai.CheckpointManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckpointManager(object):
    """Checkpoint Manager Service
    """

    @staticmethod
    def StoreCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.CheckpointManager/StoreCheckpoint',
            distribai__pb2.StoreCheckpointRequest.SerializeToString,
            distribai__pb2.StoreCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.CheckpointManager/LoadCheckpoint',
            distribai__pb2.LoadCheckpointRequest.SerializeToString,
            distribai__pb2.LoadCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCheckpoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.CheckpointManager/ListCheckpoints',
            distribai__pb2.ListCheckpointsRequest.SerializeToString,
            distribai__pb2.ListCheckpointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CreditEngineStub(object):
    """Credit Engine Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBalance = channel.unary_unary(
                '/distribai.CreditEngine/GetBalance',
                request_serializer=distribai__pb2.CreditBalanceRequest.SerializeToString,
                response_deserializer=distribai__pb2.CreditBalanceResponse.FromString,
                _registered_method=True)
        self.RecordContribution = channel.unary_unary(
                '/distribai.CreditEngine/RecordContribution',
                request_serializer=distribai__pb2.CreditTransactionRequest.SerializeToString,
                response_deserializer=distribai__pb2.CreditTransactionResponse.FromString,
                _registered_method=True)
        self.VerifyLedger = channel.unary_unary(
                '/distribai.CreditEngine/VerifyLedger',
                request_serializer=distribai__pb2.VerifyLedgerRequest.SerializeToString,
                response_deserializer=distribai__pb2.VerifyLedgerResponse.FromString,
                _registered_method=True)


class CreditEngineServicer(object):
    """Credit Engine Service
    """

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordContribution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyLedger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreditEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=distribai__pb2.CreditBalanceRequest.FromString,
                    response_serializer=distribai__pb2.CreditBalanceResponse.SerializeToString,
            ),
            'RecordContribution': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordContribution,
                    request_deserializer=distribai__pb2.CreditTransactionRequest.FromString,
                    response_serializer=distribai__pb2.CreditTransactionResponse.SerializeToString,
            ),
            'VerifyLedger': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyLedger,
                    request_deserializer=distribai__pb2.VerifyLedgerRequest.FromString,
                    response_serializer=distribai__pb2.VerifyLedgerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribai.CreditEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distribai.CreditEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CreditEngine(object):
    """Credit Engine Service
    """

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.CreditEngine/GetBalance',
            distribai__pb2.CreditBalanceRequest.SerializeToString,
            distribai__pb2.CreditBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordContribution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.CreditEngine/RecordContribution',
            distribai__pb2.CreditTransactionRequest.SerializeToString,
            distribai__pb2.CreditTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyLedger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.CreditEngine/VerifyLedger',
            distribai__pb2.VerifyLedgerRequest.SerializeToString,
            distribai__pb2.VerifyLedgerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthMonitorStub(object):
    """Health Monitor Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportHealth = channel.unary_unary(
                '/distribai.HealthMonitor/ReportHealth',
                request_serializer=distribai__pb2.NodeHealth.SerializeToString,
                response_deserializer=distribai__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetClusterHealth = channel.unary_unary(
                '/distribai.HealthMonitor/GetClusterHealth',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=distribai__pb2.ClusterHealth.FromString,
                _registered_method=True)
        self.GetServiceHealth = channel.unary_unary(
                '/distribai.HealthMonitor/GetServiceHealth',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=distribai__pb2.ServiceHealthList.FromString,
                _registered_method=True)


class HealthMonitorServicer(object):
    """Health Monitor Service
    """

    def ReportHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHealth,
                    request_deserializer=distribai__pb2.NodeHealth.FromString,
                    response_serializer=distribai__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetClusterHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterHealth,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=distribai__pb2.ClusterHealth.SerializeToString,
            ),
            'GetServiceHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceHealth,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=distribai__pb2.ServiceHealthList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distribai.HealthMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distribai.HealthMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthMonitor(object):
    """Health Monitor Service
    """

    @staticmethod
    def ReportHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.HealthMonitor/ReportHealth',
            distribai__pb2.NodeHealth.SerializeToString,
            distribai__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.HealthMonitor/GetClusterHealth',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            distribai__pb2.ClusterHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distribai.HealthMonitor/GetServiceHealth',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            distribai__pb2.ServiceHealthList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
