apiVersion: v1
kind: Secret
metadata:
  name: {{ include "distribai.fullname" . }}-secrets
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.env.JWT_SECRET | quote }}
  SIGNING_KEY: {{ .Values.env.SIGNING_KEY | quote }}
  REDIS_URL: {{ .Values.env.REDIS_URL | quote }}
  ADMIN_HOST: {{ .Values.env.ADMIN_HOST | quote }}
  ADMIN_REQUIRE_AUTH: {{ .Values.env.ADMIN_REQUIRE_AUTH | quote }}
  DISTRIBAI_ADMIN_SECRET: {{ .Values.env.DISTRIBAI_ADMIN_SECRET | quote }}
